<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Arun_pal" failures="1" tests="5" name="Surefire test" time="65.598" errors="0" timestamp="2023-04-28T22:58:24 IST">
  <testcase classname="tpack.BookAnItemTest" name="bookingPhone" time="20.283"/>
  <testcase classname="tpack.LoginTest" name="login" time="2.288"/>
  <testcase classname="tpack.LoginTest" name="login" time="10.938"/>
  <testcase classname="tpack.RegisterAccountTest" name="registerAccount" time="1.892"/>
  <testcase classname="tpack.RegisterAccountTest" name="registerAccount" time="4.193">
    <failure type="java.lang.AssertionError" message="expected [Failure] but found [Successfull]">
      <![CDATA[java.lang.AssertionError: expected [Failure] but found [Successfull]
at tpack.RegisterAccountTest.registerAccount(RegisterAccountTest.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- registerAccount -->
</testsuite> <!-- Surefire test -->
